services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow-tracking-server
    ports:
      - "5555:5555"
    volumes:
      - ./mlruns:/mlflow/mlruns
      - ./mlflow_storage:/mlflow/storage
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5555
      --backend-store-uri sqlite:////mlflow/storage/mlflow.db
      --default-artifact-root file:///mlflow/mlruns
